module.exports = {
  "parser": "babel-eslint",

  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },

  "plugins": [
    "react",
    "babel"
  ],

  "rules": {
    "brace-style": [2, "1tbs", { "allowSingleLine": true }],
    "camelcase": [1],
    "comma-dangle": [0],
    "comma-spacing": [1, {"before": false, "after": true}],
    "comma-style": [2, "last"],
    "consistent-this": [0, "self"],
    "curly": [2, "multi-line"],
    "default-case": [2],
    "dot-notation": [1, { "allowKeywords": false }],
    "eol-last": [1],
    "eqeqeq": [2],
    "generator-star-spacing": [2, "after"],
    "jsx-quotes": [1, "prefer-single"],
    "quotes": [2, "single", "avoid-escape"],
    "new-parens": [2],
    "new-cap": [2],
    "no-alert": [2],
    "no-array-constructor": [2],
    "no-caller": [2],
    "no-catch-shadow": [2],
    "no-console": [0],
    "no-constant-condition": [1],
    "no-empty-label": [2],
    "no-eval": [2],
    "no-extend-native": [1],
    "no-extra-bind": [2],
    "no-extra-boolean-cast": [2],
    "no-extra-semi": [1],
    "no-floating-decimal": [2],
    "no-implied-eval": [2],
    "no-iterator": [2],
    "no-label-var": [2],
    "no-labels": [2],
    "no-lone-blocks": [2],
    "no-loop-func": [2],
    "no-multi-spaces": [2],
    "no-multi-str": [2],
    "no-multiple-empty-lines": [1, { "max": 2 }],
    "no-native-reassign": [1],
    "no-new-func": [2],
    "no-new-object": [2],
    "no-new-wrappers": [2],
    "no-process-exit": [2],
    "no-proto": [2],
    "no-return-assign": [2],
    "no-sequences": [2],
    "no-shadow": [1],
    "no-shadow-restricted-names": [2],
    "no-spaced-func": [2],
    "no-throw-literal": [2],
    "no-trailing-spaces": [1],
    "no-undef-init": [2],
    "no-underscore-dangle": [1],
    "no-unused-expressions": [2],
    "no-unused-vars": [1, { "vars": "all", "args": "none" }],
    "no-use-before-define": [2, "nofunc"],
    "no-with": [2],
    "one-var": [1, { "var": "always", "let": "never", "const": "never" }],
    "operator-linebreak": [2, "after"],
    "semi": [2],
    "semi-spacing": [2, { "before": false, "after": true }],
    "space-after-keywords": [2, "always"],
    "space-before-function-paren": [1, { "anonymous": "always", "named": "never" }],
    "space-in-parens": [1, "never"],
    "space-infix-ops": [2],
    "space-return-throw-case": [2],
    "space-unary-ops": [2, { "words": true, "nonwords": false }],
    "strict": [2, "function"],
    "wrap-iife": [2],
    "wrap-regex": [2],
    "yoda": [2, "never", { "exceptRange": true }],
    "react/display-name": 1,
    "react/jsx-boolean-value": 0,
    "react/jsx-no-undef": 1,
    "react/jsx-sort-props": 0,
    "react/jsx-sort-prop-types": 0,
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/no-did-mount-set-state": 1,
    "react/no-did-update-set-state": 1,
    "react/no-multi-comp": 1,
    "react/no-unknown-property": 1,
    "react/prop-types": 0,
    "react/react-in-jsx-scope": 1,
    "react/self-closing-comp": 1,
    "react/sort-comp": 0,
    "react/wrap-multilines": 1,
    "babel/new-cap": 1,
    "babel/object-curly-spacing": 0
  }
};
